"""
Unit tests for parsers.
"""

import pytest
from pathlib import Path
from sha1hulud_scanner.parsers import (
    DatabaseParser,
    NpmParser,
    YarnParser,
    PnpmParser,
)
from sha1hulud_scanner.models import LockFileType


class TestDatabaseParser:
    def test_initialization_error(self, tmp_path):
        """Test initialization with invalid path."""
        with pytest.raises(FileNotFoundError):
            DatabaseParser(tmp_path / "nonexistent")
            
        file_path = tmp_path / "file"
        file_path.touch()
        with pytest.raises(ValueError):
            DatabaseParser(file_path)

    def test_load_packages_md(self, tmp_path):
        """Test loading from packages.md."""
        db_dir = tmp_path / "db"
        db_dir.mkdir()
        
        md_file = db_dir / "packages.md"
        md_file.write_text(
            "- package-a@1.0.0\n"
            "- @scope/package-b@2.0.0\n"
            "- invalid-entry\n"  # Should be skipped
            "- pkg@\n"  # Should be skipped
        , encoding="utf-8")
        
        parser = DatabaseParser(db_dir)
        vuln_set, vuln_dict = parser.load_all()
        
        assert ("package-a", "1.0.0") in vuln_set
        assert ("@scope/package-b", "2.0.0") in vuln_set
        assert len(vuln_set) == 2
        
        assert "package-a" in vuln_dict
        assert "1.0.0" in vuln_dict["package-a"]

    def test_load_wiz_csv(self, tmp_path):
        """Test loading from wiz-packages.csv."""
        db_dir = tmp_path / "db"
        db_dir.mkdir()
        
        csv_file = db_dir / "wiz-packages.csv"
        csv_file.write_text(
            "Package,Version\n"
            "package-c,= 3.0.0\n"
            "package-d,= 4.0.0 || = 4.1.0\n"
        , encoding="utf-8")
        
        parser = DatabaseParser(db_dir)
        vuln_set, vuln_dict = parser.load_all()
        
        assert ("package-c", "3.0.0") in vuln_set
        assert ("package-d", "4.0.0") in vuln_set
        assert ("package-d", "4.1.0") in vuln_set
        assert len(vuln_set) == 3


class TestNpmParser:
    def test_properties(self):
        parser = NpmParser()
        assert parser.file_type == LockFileType.NPM
        assert parser.filename == "package-lock.json"

    def test_parse_v1(self, tmp_path):
        """Test parsing npm lockfile v1."""
        lock_file = tmp_path / "package-lock.json"
        lock_file.write_text("""
        {
            "lockfileVersion": 1,
            "dependencies": {
                "pkg-a": {
                    "version": "1.0.0"
                },
                "pkg-b": {
                    "version": "2.0.0",
                    "dependencies": {
                        "pkg-c": {
                            "version": "3.0.0"
                        }
                    }
                }
            }
        }
        """, encoding="utf-8")
        
        parser = NpmParser()
        packages = parser.parse(lock_file)
        
        assert len(packages) == 3
        names = {p.name for p in packages}
        assert "pkg-a" in names
        assert "pkg-b" in names
        assert "pkg-c" in names

    def test_parse_v2(self, tmp_path):
        """Test parsing npm lockfile v2."""
        lock_file = tmp_path / "package-lock.json"
        lock_file.write_text("""
        {
            "lockfileVersion": 2,
            "packages": {
                "": {"name": "root"},
                "node_modules/pkg-a": {
                    "version": "1.0.0"
                },
                "node_modules/@scope/pkg-b": {
                    "version": "2.0.0"
                }
            }
        }
        """, encoding="utf-8")
        
        parser = NpmParser()
        packages = parser.parse(lock_file)
        
        assert len(packages) == 2
        names = {p.name for p in packages}
        assert "pkg-a" in names
        assert "@scope/pkg-b" in names


class TestYarnParser:
    def test_properties(self):
        parser = YarnParser()
        assert parser.file_type == LockFileType.YARN
        assert parser.filename == "yarn.lock"

    def test_parse(self, tmp_path):
        """Test parsing yarn.lock."""
        lock_file = tmp_path / "yarn.lock"
        lock_file.write_text("""
        # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
        # yarn lockfile v1


        "pkg-a@^1.0.0":
          version "1.0.0"
          resolved "https://registry.yarnpkg.com/pkg-a/-/pkg-a-1.0.0.tgz#..."
          integrity sha512-...

        "@scope/pkg-b@^2.0.0", "@scope/pkg-b@^2.1.0":
          version "2.1.0"
          resolved "https://registry.yarnpkg.com/@scope/pkg-b/-/pkg-b-2.1.0.tgz#..."
          integrity sha512-...
        """, encoding="utf-8")
        
        parser = YarnParser()
        packages = parser.parse(lock_file)
        
        assert len(packages) == 2
        
        pkg_a = next(p for p in packages if p.name == "pkg-a")
        assert pkg_a.version == "1.0.0"
        
        pkg_b = next(p for p in packages if p.name == "@scope/pkg-b")
        assert pkg_b.version == "2.1.0"


class TestPnpmParser:
    def test_properties(self):
        parser = PnpmParser()
        assert parser.file_type == LockFileType.PNPM
        assert parser.filename == "pnpm-lock.yaml"

    def test_parse(self, tmp_path):
        """Test parsing pnpm-lock.yaml."""
        lock_file = tmp_path / "pnpm-lock.yaml"
        lock_file.write_text("""
        lockfileVersion: '6.0'
        
        packages:
          /pkg-a@1.0.0:
            resolution: {integrity: sha512-...}
          /@scope/pkg-b@2.0.0:
            resolution: {integrity: sha512-...}
        """, encoding="utf-8")
        
        parser = PnpmParser()
        packages = parser.parse(lock_file)
        
        assert len(packages) == 2
        names = {p.name for p in packages}
        assert "pkg-a" in names
        assert "@scope/pkg-b" in names
